### ISSUE TITLE
Create a docs.targetvalidation.org, with content independent from the webapp code.

### ISSUE THREAD

**Issue by elipapa** [opentargets/webapp#91]
It would be great to have a system for FAQ and documentation (scoring, data sources and API), which allowed content to be updated independent of our code repo. 

Imho it should:
- [ ] update live and independently from a code repo
- [ ] be easy to edit for a non-coder
- [ ] allow search
- [ ] be easy to navigate
- [ ] allow for rich formatting and diagram

I have copied our current FAQ to gitbook.com as an example, available at https://opentargets.gitbooks.io/faq/content/

![image](https://cloud.githubusercontent.com/assets/112610/23508014/a79e7f56-ff47-11e6-9d93-edf326ead076.png)

but any tool fit for the purpose would be fine.

cc @emepyc @deniseOme @DaveHulcoop

**Comment by deniseOme** [comment]
We've fewer than 20 FAQs. We may want to combine them into categories (e.g user interface, data, API, etc...)

**Comment by elipapa** [comment]
i think we should really do this. gitbook.com is a bit stale if you look at their github. alternatives I found were https://docsify.js.org/#/ and https://docute.js.org/#/home
any other suggestions?
cc @peatroot @LucaFumis

**Comment by elipapa** [comment]
from slack:

@elipapa:
 I made a shortlist of the tools we could use to make docs.targetvalidation.org happen. I filtered out all the ones with few users or few stars in github. In rough order of (my) preference they are:
- gitbook
- mkdoc (https://github.com/mkdocs/mkdocs check the themes too https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)
-  docsify https://docsify.js.org/#/
- daux.io https://dauxio.github.io/
- jekyll static site + angolia search (https://community.algolia.com/jekyll-algolia/)

search seems easy to add to anything with the free algolia service (https://community.algolia.com/docsearch/) so let’s choose based on the rest.

What do you guys think? I’d like to choose one and start testing out options next week.

@peatroot : [10:58 AM]
gitbook or docsify would be my choice, followed by mkdoc. daux uses php, which I've never used.

@andrewhercules  [11:05 AM]
I'd say Gitbook or MKDocs. I'm impressed with their search functionality - something I think will be important for our docs. And the UI options are good too - they both have templates or themes you can use as a base. And MKDocs is well maintained in my opinion - seems to be a good community working on bugs and issues.
[11:06 AM]
Docsify is interesting - while I like the JS aspect, the search functionality and UI isn't as useful as Gitbook or MKDocs - search results appear in the left column making it more difficult to read.

@elipapa [11:18 AM]
it’s true that gitbook seems to have gone through a slump, but it seems that a new version is shipping at the end of this month (https://github.com/GitbookIO/gitbook/issues/1962) and they have a large plugin community (https://plugins.gitbook.com/browse).
i have just signed up for beta and will wait to see.
[11:18 AM]
we have a test account here => https://www.gitbook.com/@opentargets/

@LucaFumis  [11:29 AM]
Out of that list I have only used Jekyll and I probably wouldn’t use for this.
gitbook / docsify / mkdoc seem viable options.
I was looking at options to generate code documentation (i.e. from the code comments - JSDocs and ESDocs seem the most common), so the ability to integrate that would be important I guess.
I understand that can be exported as markdown, which can then be imported in gitbook or docsify.
obviously that is if we want to include code documentation in this documentation.

**Comment by elipapa** [comment]
more compelling users of gitbook: http://airbnb.io/react-sketchapp/#

we don't have to host on gitbook.com either.. it can be deployed on netlify for eg. https://www.netlify.com/blog/2015/12/08/a-step-by-step-guide-gitbook-on-netlify/

**Comment by elipapa** [comment]
Take a look at the version deployed on gitbook.com:
https://docs.opentargets.io/

## edits
cc/ @deniseOme 
The content of the site is on git. There are two remotes, in sync with each other, [one on github](https://github.com/opentargets/docs.targetvalidation.org) and one on gitbook server. 

You could edit our repo, but it's easier to use gitbook.com editor, at least for now.
Downloading the desktop editor (or using the gitbook editor) allows to edit the remote on gitbook.com and it's currently the preferred way. 

## deploying
Customization can be done using a `book.json` file. see https://toolchain.gitbook.com/config.html
Some examples of this is done are [here](https://github.com/airbnb/react-sketchapp/blob/master/package.json) and [there](https://github.com/airbnb/react-sketchapp/blob/master/book.json).
 
It does not seem worth it to publish on netlify, at least performance wise. 

netlify:
![image](https://user-images.githubusercontent.com/112610/35444233-c353ffac-02a5-11e8-8a5d-fba09280bcaa.png)
gitbook.com
![image](https://user-images.githubusercontent.com/112610/35444272-e5b72448-02a5-11e8-9b91-4236db49a30b.png)

**Comment by elipapa** [comment]
moved the DNS to docs.targetvalidation.org and linked it from the platform with a suggested change https://github.com/opentargets/webapp/pull/254
